AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a VPC with two public subnets

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value: "projects.aws.alb-lambda"
        - Key: "CostCenter"
          Value: "projects.aws.alb-lambda"

  # Public subnets (placed in 1 az randomly)
  PublicSubA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: "CostCenter"
          Value: "projects.aws.alb-lambda"

  PublicSubB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: "Name"
          Value: "projects.aws.alb-lambda"
        - Key: "CostCenter"
          Value: "projects.aws.alb-lambda"

  # Internet gateway and attachment to VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "projects.aws.alb-lambda"
        - Key: "CostCenter"
          Value: "projects.aws.alb-lambda"

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public routing table and routes with subnet associations
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value: "projects.aws.alb-lambda"
        - Key: "CostCenter"
          Value: "projects.aws.alb-lambda"

  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTablePublic

  RouteTableAssocSubnetPublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubA

  RouteTableAssocSubnetPublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubB

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: AlbLambdaVpcId
  PublicSubnetA:
    Value: !Ref PublicSubA
    Export:
      Name: AlbLambdaPublicSubnetA
  PublicSubnetB:
    Value: !Ref PublicSubB
    Export:
      Name: AlbLambdaPublicSubnetB
