Description: ALB And Lambdas
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-003e6ce74c0ec695d, sg-039879afee519f8a8
  SubnetIds:
    Type: CommaDelimitedList
    Default: subnet-01405f62e49e3721d, subnet-03a2d434cd2925e93, subnet-095ddd203f02bcfa2, subnet-0cc9d8c14b31e5042, subnet-0f9184e762d15e064, subnet-0a11cbaf3d16480a1
  VpcId:
    Type: String
    Default: vpc-0836c2a075ecb38cc

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: events-admin-service-lb
      SecurityGroups: !Ref SecurityGroupIds
      Subnets: !Ref SubnetIds
      Tags:
        - Key: "CostCenter"
          Value: "services.events-admin-service"

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: events-admin-service-tg
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /actuator/health
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "300"
      Tags:
        - Key: "CostCenter"
          Value: "services.events-admin-service"

  LoadBalancerListener:
    DependsOn: [LoadBalancer, LoadBalancerTargetGroup]
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Protocol: HTTP
      # Certificate: arn:aws:acm:us-east-1:654918520080:certificate/b4d67bb3-5d56-4d5e-bf83-cdf7cb04d4ba
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup

Outputs:
  EventsAdminServiceLoadBalancerHostedZoneId:
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
    Export:
      Name: EventsAdminServiceLoadBalancerHostedZoneId
  EventsAdminServiceLoadBalancerDnsName:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: EventsAdminServiceLoadBalancerDnsName
  EventsAdminServiceLoadBalancerTargetGroup:
    Value: !Ref LoadBalancerTargetGroup
    Export:
      Name: EventsAdminServiceLoadBalancerTargetGroup
